edition = "2024"
hard_tabs = true
merge_derives = true
reorder_imports = true
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Crate"
group_imprts = "StdExternalCrate"
reorder_modules = true
use_field_init_shorthand = true
use_small_heuristics = "Off"
indent_style = "Block"
match_arm_blocks = true
reorder_impl_items = true
wrap_comments = true